### ISSUE TITLE
Selecting between Topo map layer and a satellite map layer

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/turbo#1]
### Todo:
- [ ] Design a button for selecting between map layers
- [ ] Create predefined map layers for Satellite and Topo
- [ ] Make sure the map is updated when switching layers
- [ ] Optional base layer(Open streetmap)
